[tool.poetry]
name = "ignorio"
version = "0.1.0"
description = ""
authors = ["Franccesco Orozco <franccesco.orozco@codingdose.info>"]

[tool.poetry.dependencies]
python = "~3.4"
requests = "^2.19"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pudb = "^2018.1"
